// clients/ws/angular/src/index.ts
// Angular bindings for @brahmaputra/ws-client.
//
//   bootstrapApplication(App, {
//     providers: [provideBrahmaputra({ url, token: () => auth.token() })],
//   });
//
//   @Component({ template: `@for (p of prices.data() | keyvalue; track p.key) {...}` })
//   class PriceBoard {
//     prices = injectLatestByKey("prices.us", { keys: ["AAPL", "MSFT"] });
//     state = injectConnectionState();
//     publish = injectPublish();
//   }
//
// The inject* functions return signals and must run in an injection
// context (a field initializer or constructor); their subscriptions end
// when the component is destroyed. For RxJS pipelines use the `$`
// observables instead. No decorators here, so the package needs no
// Angular compiler and works in AOT, JIT and zoneless apps alike.

import {
  DestroyRef,
  InjectionToken,
  inject,
  makeEnvironmentProviders,
  signal,
  type EnvironmentProviders,
  type Signal,
} from "@angular/core";
import { Observable } from "rxjs";
import {
  BrahmaputraClient,
  latestByKey,
  recentRecords,
  type Ack,
  type BrahmaputraError,
  type ClientOptions,
  type ConnectionState,
  type FeedRecord,
  type FeedStore,
  type PublishOptions,
  type StoreOptions,
  type SubscribeOptions,
} from "@brahmaputra/ws-client";

export const BRAHMAPUTRA = new InjectionToken<BrahmaputraClient>("BrahmaputraClient");

/**
 * Provide one client to the application, connected on first use and
 * closed with the application. `options` may be a factory, which runs in an
 * injection context (so it can inject your auth service).
 */
export function provideBrahmaputra(
  options: ClientOptions | (() => ClientOptions),
): EnvironmentProviders {
  return makeEnvironmentProviders([
    {
      provide: BRAHMAPUTRA,
      useFactory: () => {
        const client = new BrahmaputraClient(typeof options === "function" ? options() : options);
        client.connect().catch(() => {
          // Surfaced through injectConnectionState / connectionState$.
        });
        inject(DestroyRef).onDestroy(() => client.close());
        return client;
      },
    },
  ]);
}

export function injectBrahmaputra(): BrahmaputraClient {
  return inject(BRAHMAPUTRA);
}

export function injectConnectionState(): Signal<ConnectionState> {
  const client = inject(BRAHMAPUTRA);
  const state = signal(client.state);
  const stop = client.onState((s) => state.set(s));
  inject(DestroyRef).onDestroy(stop);
  return state.asReadonly();
}

export interface FeedSignals<T> {
  data: Signal<T>;
  error: Signal<BrahmaputraError | null>;
  lagged: Signal<number>;
}

function injectFeed<T>(store: FeedStore<T>): FeedSignals<T> {
  const data = signal(store.get());
  const error = signal<BrahmaputraError | null>(null);
  const lagged = signal(0);
  store.subscribe(() => {
    data.set(store.get());
    error.set(store.error);
    lagged.set(store.lagged);
  });
  inject(DestroyRef).onDestroy(() => store.close());
  return { data: data.asReadonly(), error: error.asReadonly(), lagged: lagged.asReadonly() };
}

/** The latest record per key as a signal: a price board, starting from the snapshot. */
export function injectLatestByKey(
  topic: string,
  options: StoreOptions = {},
): FeedSignals<ReadonlyMap<string, FeedRecord>> {
  return injectFeed(latestByKey(inject(BRAHMAPUTRA), topic, options));
}

/** The last `limit` records, oldest first, as a signal: a trade tape, a chat. */
export function injectRecentRecords(
  topic: string,
  options: StoreOptions & { limit?: number } = {},
): FeedSignals<readonly FeedRecord[]> {
  return injectFeed(recentRecords(inject(BRAHMAPUTRA), topic, options));
}

export function injectPublish(): (message: PublishOptions) => Promise<Ack> {
  const client = inject(BRAHMAPUTRA);
  return (message) => client.publish(message);
}

// -- RxJS -------------------------------------------------------------------

function store$<T>(make: () => FeedStore<T>): Observable<T> {
  return new Observable<T>((subscriber) => {
    const store = make();
    const unsubscribe = store.subscribe(() => {
      if (store.error) subscriber.error(store.error);
      else subscriber.next(store.get());
    });
    return () => {
      unsubscribe();
      store.close();
    };
  });
}

/** Every record of `topic` as it arrives. Unsubscribing ends the subscription. */
export function records$(
  client: BrahmaputraClient,
  topic: string,
  options: SubscribeOptions = {},
): Observable<FeedRecord> {
  return new Observable<FeedRecord>((subscriber) => {
    const sub = client.subscribe(
      topic,
      {
        onRecord: (r) => subscriber.next(r),
        onError: (e) => subscriber.error(e),
      },
      options,
    );
    return () => sub.unsubscribe();
  });
}

/** The latest record per key, emitted on every change. */
export function latestByKey$(
  client: BrahmaputraClient,
  topic: string,
  options: StoreOptions = {},
): Observable<ReadonlyMap<string, FeedRecord>> {
  return store$(() => latestByKey(client, topic, options));
}

export function recentRecords$(
  client: BrahmaputraClient,
  topic: string,
  options: StoreOptions & { limit?: number } = {},
): Observable<readonly FeedRecord[]> {
  return store$(() => recentRecords(client, topic, options));
}

export function connectionState$(client: BrahmaputraClient): Observable<ConnectionState> {
  return new Observable<ConnectionState>((subscriber) => {
    subscriber.next(client.state);
    return client.onState((s) => subscriber.next(s));
  });
}

export {
  BrahmaputraClient,
  type Ack,
  type ClientOptions,
  type ConnectionState,
  type FeedRecord,
  type PublishOptions,
} from "@brahmaputra/ws-client";

// clients/ws/react/src/index.tsx
// React bindings for @brahmaputra/ws-client.
//
//   <BrahmaputraProvider options={{ url, token: getToken }}>
//     <PriceBoard />
//   </BrahmaputraProvider>
//
//   function PriceBoard() {
//     const { data: prices } = useLatestByKey("prices.us", { keys: ["AAPL", "MSFT"] });
//     const publish = usePublish();
//     ...
//   }
//
// Every hook reads through useSyncExternalStore, so concurrent rendering
// never tears, and every subscription ends when its component unmounts.

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from "react";
import {
  BrahmaputraClient,
  latestByKey,
  recentRecords,
  type Ack,
  type BrahmaputraError,
  type ClientOptions,
  type ConnectionState,
  type FeedRecord,
  type FeedStore,
  type PublishOptions,
  type StoreOptions,
  type SubscribeOptions,
  type SubscriptionHandlers,
} from "@brahmaputra/ws-client";

const Context = createContext<BrahmaputraClient | null>(null);

export type ProviderProps =
  | { client: BrahmaputraClient; options?: undefined; children?: ReactNode }
  | { options: ClientOptions; client?: undefined; children?: ReactNode };

/**
 * Makes a client available to the tree and keeps it connected while
 * mounted. Pass `options` to have the provider own the client (closed on
 * unmount), or a `client` you manage yourself.
 */
export function BrahmaputraProvider(props: ProviderProps) {
  const [client] = useState(() => props.client ?? new BrahmaputraClient(props.options!));
  const owned = props.client === undefined;
  useEffect(() => {
    client.connect().catch(() => {
      // Surfaced through useConnectionState / useConnectionError.
    });
    return () => {
      if (owned) client.close();
    };
  }, [client, owned]);
  return <Context.Provider value={client}>{props.children}</Context.Provider>;
}

/** The client from the nearest BrahmaputraProvider. */
export function useBrahmaputra(): BrahmaputraClient {
  const client = useContext(Context);
  if (!client) throw new Error("useBrahmaputra must be used inside <BrahmaputraProvider>");
  return client;
}

/** "connecting" | "open" | "reconnecting" | "closed" (and "idle" before connect). */
export function useConnectionState(): ConnectionState {
  const client = useBrahmaputra();
  return useSyncExternalStore(
    (onChange) => client.onState(onChange),
    () => client.state,
    () => client.state,
  );
}

/** Why the connection last failed, while it is not open. */
export function useConnectionError(): unknown {
  const state = useConnectionState();
  const client = useBrahmaputra();
  return state === "open" ? null : client.error;
}

export interface FeedResult<T> {
  data: T;
  /** Set if the gateway refused the subscription (e.g. TOPIC_NOT_ALLOWED). */
  error: BrahmaputraError | null;
  /** Records skipped because this client fell behind the feed. */
  lagged: number;
}

const noSubscribe = () => () => {};

function useFeed<T>(
  make: (client: BrahmaputraClient) => FeedStore<T>,
  deps: unknown[],
  empty: T,
): FeedResult<T> {
  const client = useBrahmaputra();
  const [store, setStore] = useState<FeedStore<T> | null>(null);
  useEffect(() => {
    const created = make(client);
    setStore(created);
    return () => created.close();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [client, ...deps]);
  const data = useSyncExternalStore(
    store ? (onChange) => store.subscribe(onChange) : noSubscribe,
    () => (store ? store.get() : empty),
    () => empty,
  );
  return { data, error: store?.error ?? null, lagged: store?.lagged ?? 0 };
}

const EMPTY_MAP: ReadonlyMap<string, FeedRecord> = new Map();
const EMPTY_LIST: readonly FeedRecord[] = [];

const keysDep = (keys?: string[]) => (keys ? keys.join("\u0000") : null);

/**
 * The latest record per key of `topic`: a price board. Starts from the
 * gateway's snapshot (the current price of every symbol) unless
 * `snapshot: false`.
 */
export function useLatestByKey(
  topic: string,
  options: StoreOptions = {},
): FeedResult<ReadonlyMap<string, FeedRecord>> {
  return useFeed(
    (client) => latestByKey(client, topic, options),
    [topic, keysDep(options.keys), options.snapshot, options.throttleMs],
    EMPTY_MAP,
  );
}

/** The last `limit` records of `topic`, oldest first: a trade tape, a chat. */
export function useRecentRecords(
  topic: string,
  options: StoreOptions & { limit?: number } = {},
): FeedResult<readonly FeedRecord[]> {
  return useFeed(
    (client) => recentRecords(client, topic, options),
    [topic, keysDep(options.keys), options.snapshot, options.throttleMs, options.limit],
    EMPTY_LIST,
  );
}

/**
 * Call `onRecord` for each record of `topic`, for as long as the component
 * is mounted. The latest handler is always used; changing it does not
 * resubscribe.
 */
export function useSubscription(
  topic: string,
  onRecord: (record: FeedRecord) => void,
  options: SubscribeOptions & Omit<SubscriptionHandlers, "onRecord"> = {},
): void {
  const client = useBrahmaputra();
  const handler = useRef(onRecord);
  handler.current = onRecord;
  const rest = useRef(options);
  rest.current = options;
  useEffect(() => {
    const sub = client.subscribe(
      topic,
      {
        onRecord: (r) => handler.current(r),
        onLag: (n) => rest.current.onLag?.(n),
        onSubscribed: (n) => rest.current.onSubscribed?.(n),
        onError: (e) => rest.current.onError?.(e),
      },
      { keys: options.keys, snapshot: options.snapshot },
    );
    return () => sub.unsubscribe();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [client, topic, keysDep(options.keys), options.snapshot]);
}

/** A stable publish function: resolves with the record's partition and offset. */
export function usePublish(): (message: PublishOptions) => Promise<Ack> {
  const client = useBrahmaputra();
  return useCallback((message: PublishOptions) => client.publish(message), [client]);
}

export {
  BrahmaputraClient,
  type Ack,
  type ClientOptions,
  type ConnectionState,
  type FeedRecord,
  type PublishOptions,
} from "@brahmaputra/ws-client";
